// Inlined results so the site opens from file:// without fetch/CORS issues.
// THIS FILE is the canonical data the site renders. (data/results.json is an
// earlier seed snapshot kept for reference; data/temporal_shift_null.json and
// data/nocache_roar.json are auxiliary snapshots and may use a different normalization
// (nocache_roar.json is ceiling-normalized, so its values differ from the raw scores rendered here).)
window.BSU_DATA = {
  "meta": {
    "title": "Brain-Score · A research framework on one unified model interface",
    "subtitle": "A research framework built on one unified Brain-Score interface. Brain-Score measures how closely an AI model resembles the brain; we rebuilt the plumbing so a model, once wired in, runs through a single shared hand-off for every evaluation: predicting brain activity (seeing, reading, listening, watching video), matching behavior, and even acting in a game or being lesioned. Brain-alignment is the core of the work; the action and game pieces are here to show that the same one interface also spans perception and action, not that a game-player is 'brain-like.' (Wiring in a brand-new kind of model is still real work; the win is that everything after that is uniform.) This page walks through what that makes possible.",
    "note": "A quick promise about honesty: every test here comes with a null baseline to beat (a model that knows nothing, or just guesses), so a good score has to be earned, not lucky. Wherever a result is shaky, surprising, or only proves the machinery runs (not that the model is truly brain-like), we say so in plain language right there, and there's a 'what to keep in mind' box at the very bottom.",
    "provenance": "How to trust the numbers: the behavior scores were re-run fresh this session and reproduced their earlier values (bit-for-bit in our regression tests); the timing and game results come from real recorded brain data and real game playthroughs; the cortical maps are generated by our own tools. Anywhere a number is carried over from earlier work or is a stand-in for illustration, it's labelled as such."
  },
  "hero_rotation": [
    {"model": "clip-vit-b-32", "benchmark": "MajajHong2015public.IT-pls", "comment": "# vision · neural: predict IT from image features"},
    {"model": "clip-vit-b-32", "benchmark": "Pereira2018.243sentences-linear", "comment": "# the SAME model, now a language benchmark"},
    {"model": "qwen2.5-vl-3b", "benchmark": "MajajHong2015public.IT-pls", "comment": "# a 3B VLM instead, identical call"},
    {"model": "gpt2", "benchmark": "Yeatman2021-lexical_decision-text", "comment": "# reading behavior, from strings alone"},
    {"model": "blip2-opt-2.7b", "benchmark": "MajajHong2015public.V4-pls", "comment": "# different model, different size, same three lines"},
    {"model": "vjepa1-vitl", "benchmark": "Lahner2024-fMRI-naturalistic-visualROI", "comment": "# video · naturalistic fMRI encoding"},
    {"model": "vjepa1-wav2vec2", "benchmark": "Lahner2024-fMRI-naturalistic-multimodal-visualROI", "comment": "# two towers (video + audio), one model object"},
    {"lines": [
      "from brainscore import load_model",
      "from brainscore.harnesses.gymnasium_harness import play_gym_episode",
      "model  = load_model(\"qwen2.5-vl-7b\")",
      "result = play_gym_episode(model, \"GridGame-5x5\")",
      "# embodied: the model emits an action from process(EnvironmentStep) each tick"
    ]},
    {"lines": [
      "from brainscore import load_model, load_benchmark",
      "model = load_model(\"qwen2.5-vl-3b\")",
      "model.process(StateChange(target=vwf_units, perturbation=\"zero\"))  # lesion",
      "score = load_benchmark(\"Yeatman2021-lexical_decision-image\")(model)",
      "# perturbation: score the lesioned model; model.reset() restores it"
    ]},
    {"model": "random-vit-b-32", "benchmark": "MajajHong2015public.IT-pls", "comment": "# even the null floor registers the same way"}
  ],
  "scaling": {
    "language_encoding": {
      "capability": "Predicting the brain: reading sentences (Pereira 2018)",
      "models": ["random-vit", "CLIP-B32", "GPT-2", "Qwen-3B", "BLIP-2"],
      "scores": [0.123, 0.464, 0.531, 0.708, 0.737],
      "null_floor": 0.123,
      "reading": "How well each model predicts the brain's language network. Even an untrained model scores a little (0.12) just from random patterns. That's the null baseline, marked on the left. The real models clear it by about 4×, and the bigger language models (Qwen, BLIP-2) predict it best. Higher is better."
    },
    "it_encoding": {
      "capability": "Predicting the brain: seeing objects (MajajHong 2015)",
      "models": ["random-vit", "Qwen-3B", "BLIP-2", "CLIP-B32"],
      "scores": [0.104, 0.315, 0.334, 0.374],
      "null_floor": 0.104,
      "reading": "How well each model predicts a high-level vision area (called IT). The surprise: bigger isn't better. CLIP, the smallest model here, predicts it best. What seems to matter is how the model was trained (CLIP learned by matching pictures to their captions), not its size. The gaps are small and we haven't formally tested whether they're real, so read this as suggestive; a result that doesn't climb with size is a reason to scrutinize the test, not a headline."
    },
    "video_encoding": {
      "capability": "Predicting the brain: watching video (Lahner 2024 BOLDMoments)",
      "models": ["BLIP-2", "Qwen-3B", "VideoMAE", "V-JEPA2", "CLIP-B32", "V-JEPA1"],
      "scores": [0.180, 0.227, 0.321, 0.421, 0.456, 0.533],
      "ci_lo": [0.1765, 0.2233, 0.3142, 0.4146, 0.4507, 0.5276],
      "ci_hi": [0.1829, 0.2303, 0.3275, 0.4283, 0.4611, 0.5382],
      "null_floor": 0.05,
      "reading": "How well each model predicts a brain watching short videos. The standout is V-JEPA v1, a video model trained to predict its own internal picture of a scene rather than to reproduce the exact pixels (VideoMAE, which does the pixel version, lands lower). So how a video model is trained matters more than whether it handles motion 'natively.' One honesty note: an earlier ranking had CLIP ahead of V-JEPA v2, and we checked whether that was just an unlucky choice of which internal layer to read. It wasn't (we tried every layer; the gap is real). The error bars are 95% bootstrap intervals over voxels: they don't overlap between V-JEPA v1, CLIP, and V-JEPA v2, so that ordering is a real difference, not noise. These are raw match scores, not adjusted for how noisy each voxel is."
    },
    "behavior_roar": {
      "capability": "Behavior: real vs. fake words (ROAR / Yeatman 2021)",
      "models": ["chance", "random-vit", "CLIP-B32", "BLIP-2", "GPT-2", "Qwen-3B"],
      "scores": [0.500, 0.540, 0.680, 0.790, 0.810, 0.930],
      "null_floor": 0.540,
      "reading": "Can each model tell real words from fake ones, the task used to screen for dyslexia? Pure guessing scores 0.50; an untrained model barely beats it (0.54). GPT-2, a text-only model that never sees images, reaches 0.81, matching humans, which tells us this task is really about knowing letter patterns, not about vision. Qwen, which answers by writing out its choice, scores highest (0.93)."
    },
    "embodied_game": {
      "capability": "Playing: grid video game",
      "models": ["random moves", "Qwen-VL 3B (CoT)", "Qwen-VL 7B (CoT)", "Gemma-4 12B (CoT)", "DeepSeek-R1 (ASCII)", "perfect player"],
      "scores": [0.20, 0.0, 0.53, 1.0, 0.87, 1.0],
      "null_floor": 0.20,
      "reading": "Can a model play a simple maze-style video game, looking at the board, picking a move, seeing what happens, then repeating? Moving at random wins about 1 in 5 (the floor); a perfect player wins every one (the 'oracle' ceiling). The three vision models all look at the same picture of the board: the small one (3B) fails completely (0.0), the medium one (7B), using chain-of-thought (CoT), wins about half (0.53), and the large one (12B) wins them all (1.0). Hand the board to a text-only model as an ASCII grid instead of an image (DeepSeek-R1) and it wins most (0.87). The lesson: for the smaller models the hard part isn't planning the route, it's seeing the board clearly from the picture, and that problem fades as the models get bigger. (15 games per model.)"
    },
    "multimodal_algonauts": {
      "capability": "Predicting the brain: watching a movie (Algonauts 2025 / CNeuroMod)",
      "models": ["text-only", "video-only", "audio-only", "combined", "banded (per-sense)"],
      "scores": [0.120, 0.150, 0.157, 0.186, 0.213],
      "null_floor": 0.05,
      "reading": "Predicting a brain watching a full movie, with picture, sound, and dialogue all at once. Each sense on its own predicts the brain a little (0.12–0.16); combining all three does better (0.19); and a smarter way of combining them, which lets each sense pull its own weight, does best (0.21). That matches the published benchmark's own baseline (about 0.20–0.25). The best published result reaches about 0.32 using a single native multimodal model. Whether that extra comes from the model itself or from a more polished pipeline, we haven't tested head-to-head. Worth knowing: an earlier version of this scored near zero, not because the senses don't help but because the model's features and the brain scans weren't lined up in time. Fixing the timing brought it up into the published range."
    }
  },
  "limitations": {
    "title": "What to keep in mind",
    "items": [
      "On the IT vision test, the scores don't climb neatly with model size. We read that as a reason to scrutinize the test, not as a finding about scaling.",
      "The headline 'V-JEPA beats CLIP on video' only holds after a particular scoring choice and picking the best internal layer; change those and the ranking can move. (One related worry we ruled out: V-JEPA's second version trailing CLIP is real, not an artifact of which layer we read. We checked every layer.)",
      "On the video test, carefully picking the 'best' neurons barely beats picking at random: the brain signal is spread across many neurons, so cherry-picking doesn't help here. (This is the opposite of the reading-neurons experiment, where the chosen neurons genuinely mattered.)",
      "The video-game size comparison (small → medium → large) is only 15 games on a small board, a clear trend but a demonstration, not a precise law. And it's one specific game; a harder maze game gives very different numbers and isn't interchangeable.",
      "The 'brain map' visual that places model neurons on a cortex layout has only been checked on made-up test data, not real brain scans, and isn't part of any scored test.",
      "We reach the published movie-prediction range but not the very best published number (~0.32). We haven't run the controlled experiment that would say whether that gap is the model or the pipeline.",
      "The brain-prediction scores are raw correlations, not adjusted for how noisy each spot in the brain is, and we don't yet have error bars, so small differences between models may not be meaningful.",
      "The 'dyslexia' effect depends on model size: it doesn't show up in the small model, barely in the medium, and clearly only in the large (32B) one. The original study saw it in an even larger model with an even gentler nudge; we haven't run that largest model."
    ]
  },
  "temporal_shift_validation": {
    "title": "A timing sanity-check, run on real brain scans",
    "subtitle": "One person watching movies in a scanner: 50,000 brain snapshots (one roughly every 1.5 seconds), matched against what an AI saw in the video",
    "shifts": [-12, -6, -3, 0, 3, 6, 12, 18],
    "scores": [0.024, 0.035, 0.055, 0.120, 0.132, 0.078, 0.040, 0.036],
    "true_delay": 3,
    "shuffle_floor": 0.009,
    "reading": "A check that we're lining things up in time correctly. When you see or hear something, your brain's response shows up in a scanner a few seconds late, because blood flow takes time to catch up to the neurons. So the AI's read on each moment of the movie only matches the brain scans when we nudge it forward by that few-second delay. The match is strongest at exactly that nudge (about 4.5 seconds) and falls off when we slide it too early or too late, in both directions. If the match had nothing to do with the movie, this curve would be flat. It isn't, which is the reassurance we wanted. (The dashed line is the match score after we deliberately scramble the timing, i.e. the no-signal floor.)"
  },
  "movie_brain": {
    "title": "Recorded vs. predicted BOLD for a held-out movie clip",
    "subtitle": "A real person watched a 10-second clip from the TV show Friends (picture, sound, and dialogue) inside an fMRI scanner that recorded their brain. We can't show the clip itself here (it's licensed footage), but we asked an AI model to predict that brain response from the very same clip. Top brain: what the person's brain actually did. Bottom brain: what the model predicted, for a clip it was never trained on. The two maps won't look pixel-for-pixel identical: the agreement is statistical (a correlation across the whole brain), and the curve below tracks how strong that match is snapshot by snapshot (each map is a snapshot of the whole brain at that moment).",
    "human": "assets/movie_brain_real/human/bold_",
    "tabs": [
      {"id": "tribe", "label": "TRIBEv2: three separate encoders combined", "model": "assets/movie_brain_real/model_tribe/bold_", "per_tr_r": [0.2825, 0.2102, 0.2143, 0.2169, 0.0562, 0.2749, 0.2863], "mean_r": 0.220},
      {"id": "qwen", "label": "Qwen3-Omni: one native multimodal model", "model": "assets/movie_brain_real/model_qwen/bold_", "per_tr_r": [0.1957, -0.0535, 0.1526, 0.1402, 0.3138, 0.4096, 0.374], "mean_r": 0.219}
    ],
    "n": 7,
    "tr_sec": 1.49,
    "cachebust": "14",
    "transcript": ["spoken", "dialogue", "from", "the", "clip", "(not", "shown)"],
    "times": [29.8, 31.3, 32.8, 34.3, 35.8, 37.2, 38.7],
    "note": "Red = a spot more active than this clip's average; blue = less active. Both brains are drawn on the same scale so you can compare them side by side; what matters is the shape of the response (which areas light up where), not the exact brightness. How close they are is captured by the single match score (≈0.22); it's measured over just 7 brain snapshots here, so treat it as rough, since the model was tuned on far more data than this short window.",
    "reading": "Use the two tabs to switch which AI model is doing the predicting. The first, 'TRIBEv2,' is really three separate encoders working together (one model for the picture, one for the sound, one for the words) whose outputs we stitch together. The second, 'Qwen3-Omni,' is a single model that takes picture, sound, and words in all at once. The interesting part: on this clip they predict the brain about equally well (a match score of 0.22 either way), so combining the senses inside one model doesn't beat three good specialists here. The match score runs from 0 (no better than chance) to about 0.4 (roughly the ceiling for today's models on this kind of data), so 0.22 is a real, if modest, match. One nuance worth knowing: the brain's response to what you see or hear shows up in a scanner a few seconds late (blood flow lags the neural activity), and the model builds that same delay in, so the two brains are lined up correctly in time and you're comparing like with like.",
    "caption": "Why this is a fair test: the model was trained on other Friends episodes and never saw this clip, so the bottom brain is a genuine prediction, not a replay. The top brain is the real recorded scan. The Friends footage belongs to the research dataset (Algonauts / Courtois NeuroMod) and isn't reproduced here, since it's licensed. (The clip is about 10 seconds: 7 brain snapshots, one roughly every 1.5 seconds.)"
  },
  "leaderboard": {
    "title": "Putting it on the public scoreboard",
    "subtitle": "Everything else on this page is scored on our own tests. The Algonauts 2025 challenge is the outside check: predict a person's brain response while they watch movies, graded by the organizers on footage the model never sees. We entered a model assembled entirely through the single hand-off (one encoder for the picture, one for the sound, one for the dialogue, their outputs combined to predict the brain) and submitted it to the live public leaderboard.",
    "indist_title": "New episodes of a familiar show",
    "indist_bars": [
      {"label": "challenge baseline", "v": 0.20},
      {"label": "our model", "v": 0.229, "ours": true},
      {"label": "best published", "v": 0.31}
    ],
    "indist_note": "Score = how well the predicted brain response matches the real one across the brain (0 = chance). On new episodes of a show the model had seen other episodes of, it clears the challenge's own published baseline; the best published result uses a purpose-built model.",
    "ood_title": "Six films it had never seen",
    "ood_bars": [
      {"label": "Chaplin (silent B&W)", "v": 0.063},
      {"label": "Wheel of Time", "v": 0.104},
      {"label": "Planet Earth", "v": 0.120},
      {"label": "Passepartout", "v": 0.125},
      {"label": "Pulp Fiction", "v": 0.144},
      {"label": "Mononoke (anime)", "v": 0.162}
    ],
    "ood_avg": 0.120,
    "ood_top": 0.23,
    "ood_note": "Average across films 0.12 (dashed line); the best published out-of-distribution result is about 0.23. Hardest on the silent black-and-white Chaplin clip (no dialogue, and footage unlike anything modern encoders are built for) and easiest on the animated film.",
    "reading": "Two things matter here. **First, this is the real test:** an outside leaderboard, graded on footage we never touched, by the people who built the benchmark, not our own scoring. A model wired together through the same hand-off as every other test on this page clears the published baseline on familiar material (0.23 vs about 0.20), and its score on held-out episodes matches what we'd measured on our own beforehand, so nothing was quietly overfit. **Second, the honest gap:** on genuinely new films the score roughly halves (0.12), well short of the best published ~0.23. That out-of-distribution gap is exactly where a stronger video encoder, or a purpose-built multimodal model like the challenge winner, earns its keep, and it's the next thing we're wiring in. The headline isn't that we won; it's that one model, assembled the same way as everything else here, lands on a public neuroscience leaderboard above its baseline.",
    "caption": "How it was built: trained to predict four people's brain responses to earlier Friends episodes from the same picture + sound + dialogue features, then asked to predict held-out Season 7 episodes (the 'familiar show' test) and six entirely new films (the 'never seen' test). Scores are the challenge's own metric: a correlation between predicted and recorded brain activity, averaged across the brain and the four people."
  },
  "nulls": {
    "description": "Every test on this page comes with a deliberately broken version of itself (the same test, but with the real signal stripped out one specific way) so we know what a null-model score looks like. A good model has to clearly beat that floor; otherwise its score is just luck or bookkeeping. Here's the broken version we use for each kind of test, and the specific mistake it's designed to catch.",
    "entries": [
      {"capability": "predicting brain activity", "null": "an untrained model, or scrambled trials", "what_it_catches": "the test accidentally leaking the answer, or a predictor that's too flexible and overfits"},
      {"capability": "behavior (e.g. real vs. fake words)", "null": "pure guessing", "what_it_catches": "an easy task, or a predictor that memorizes the training set"},
      {"capability": "movies / multiple senses over time", "null": "deliberately mis-time the AI vs. the brain", "what_it_catches": "a match that's a timing coincidence; it must fall apart when mis-timed"},
      {"capability": "switching off neurons (the dyslexia test)", "null": "switch off the same number of random neurons", "what_it_catches": "general clumsy damage masquerading as a specific, targeted effect"},
      {"capability": "picking out special neurons", "null": "pick the same number at random", "what_it_catches": "claiming a group is special when random ones work just as well"},
      {"capability": "playing the video game", "null": "move at random", "what_it_catches": "a game so easy that flailing wins"}
    ]
  },
  "ablation": {
    "capability": "Giving an AI 'dyslexia' on purpose, by switching off its word-selective units (reproducing Honarmand et al. 2026)",
    "protocol": "First we find the model's 'reading' neurons: the internal units that respond more to real words than to scrambled letters or simple drawings. Then we switch exactly those off and check whether the model can still tell real words from fake ones. The crucial control: we also switch off the same number of randomly-chosen neurons. If only the reading-neuron version breaks reading, the damage is specific. We made it dyslexic, not just generally worse. Nothing is retrained; we just turn neurons off and watch. (The lesioned-units line is one deterministic run, so it carries no error bars; the random control is averaged over several random picks, and its spread is shown.)",
    "mask_pct": [0, 6.9, 15, 25],
    "vwf_roar": [0.975, 0.963, 0.925, 0.537],
    "vwf_roar_sd": [0.0, 0.0, 0.0, 0.0],
    "random_roar": [0.975, 0.956, 0.938, 0.887],
    "random_roar_sd": [0.0, 0.006, 0.037, 0.075],
    "vwf_control": [0.87, 0.87, 0.87, 0.80],
    "random_control": [0.87, 0.87, 0.80, 0.80],
    "threshold": 0.65,
    "brain_caption": "Where this lands in a real brain: the model's word-selective units line up with the brain's actual reading area, a patch on the lower-left of the human brain (the 'Visual Word Form Area') that's known to be central to reading. This picture highlights that patch, the territory effectively switched off when we disable the model's word-selective units.",
    "scale_note": "It only works once the model is big enough. The small model (3B) doesn't show it. The medium one (7B) bends the right way but not enough. Only the large one (32B, shown) clearly tips into 'dyslexic.' That mirrors the original study, where an even larger model needed an even smaller nudge: the bigger the model, the less damage it takes.",
    "reading": "It works: switching off the word-selective units drops the model's reading accuracy to 0.54, past the line (0.65) below which a human would be called dyslexic, while switching off the same number of random neurons barely dents it (0.89), and a separate non-reading task is left mostly intact. So we didn't just make the model worse at everything; we made it specifically bad at reading, the way dyslexia is specific. And the effect only appears once the model is large enough (see the note at left).\n\nThis is now a built-in Brain-Score test (the Yeatman2021-induced_dyslexia benchmark): it automatically finds the word-selective units, switches them off, and, crucially, checks the random-neuron control before declaring 'dyslexia,' so simply damaging the model in a clumsy way never gets mistaken for the real, specific effect. We verified end-to-end that the control does its job: when an overly-broad switch-off hurt reading non-specifically, the test correctly refused to call it dyslexia."
  },
  "selection": {
    "capability": "Gathering a model's 'reading' neurons from wherever they live",
    "layers": ["layer 5", "layer 10", "layer 16", "layer 20"],
    "selected_counts": [3, 50, 120, 18],
    "units_per_layer": 1024,
    "reading": "A model is built in stacked layers, like an assembly line. Instead of assuming the neurons we care about all sit in one layer, we let the tool collect them from wherever they actually are and treat that scattered group as a single functional unit. Here the model's word-word-selective units cluster in the middle-to-late layers, peaking around layer 16, which is where, in this kind of network, words have been recognized but not yet turned back into output."
  },
  "tools": {
    "title": "The tools that make this work",
    "subtitle": "Behind the demos sit a few reusable tools: the reason one model can be tested every which way on this page, and the reason adding a new model is mostly setup rather than custom code. Two of them do their work before any test even runs (shown here); two let us look inside a test as it happens (shown just below).",
    "autoreg": {
      "tag": "Tool 1 · Plug a model in",
      "name": "Auto-setup",
      "caption": "Point it at any model and it works out the rest: what kind of model it is, which of its inner layers are worth reading, and how to read them. What comes out is a sensible starting point that the next tool fine-tunes. Tellingly, on the two models we'd already wired up by hand, it rediscovered the very same setup on its own."
    },
    "layermap": {
      "tag": "Tool 2 · Match a layer to a brain area",
      "name": "Layer mapping",
      "caption": "A model has many inner layers, and only some line up with a given brain area. This scores every layer against the brain on one set of clips and keeps the best, then re-checks it on a completely separate set, so a layer is never graded on the very clips that picked it. The full results are just below."
    }
  },
  "layer_mapping": {
    "title": "Which way of reading the model into a brain area works best?",
    "subtitle": "A video model (V-JEPA2) predicting a brain watching short clips. There are four ways to connect it: read a whole layer, read several layers, hand-pick the best neurons in one layer, or pick the best neurons across several. To compare them fairly we removed the two things that used to muddy the picture: we tuned the readout's strength separately for each voxel (so a bigger set of neurons is no longer unfairly penalised), and we score every option on the same scale, its share of the signal that's even possible to predict (1.0 = a perfect model). We also pick the neurons on one set of clips and grade on a separate set, and shadow every choice with a same-size random pick.",
    "approaches_title": "How well each way of reading the model scores, as you give it more neurons",
    "metric_note": "Scored properly: the readout's strength is tuned per voxel (removing the old 'fewer neurons looks better' artefact), and the score is the share of the explainable signal the readout captures (1.0 = perfect). Higher is better, and now the heights ARE directly comparable.",
    "per_layer_r": [0.2426, 0.2483, 0.2561, 0.2685, 0.2672, 0.269, 0.276, 0.2888, 0.2917, 0.3033, 0.326, 0.3383, 0.3608, 0.3777, 0.4033, 0.4054, 0.4107, 0.4026, 0.3885, 0.3811, 0.3752, 0.3384, 0.3298, 0.3219],
    "best_layer": 16,
    "best_r": 0.4107,
    "current_layer": 16,
    "budget_curve": {
      "x_title": "number of neurons used to read the model",
      "y_title": "Brain-Score (0–1)",
      "budgets": [16, 32, 64, 100, 128, 256, 512, 1024],
      "within": [0.6224, 0.6645, 0.6992, 0.7200, 0.7307, 0.7470, 0.7689, 0.7765],
      "within_random": [0.4672, 0.5873, 0.6566, 0.7023, 0.7169, 0.7485, 0.7685, 0.7765],
      "pooled": [0.5451, 0.6337, 0.6968, 0.7147, 0.7221, 0.7453, 0.7625, 0.7668],
      "pooled_random": [0.4572, 0.5760, 0.6527, 0.6917, 0.7062, 0.7386, 0.7574, 0.7681],
      "whole_layer": 0.7765,
      "several_layers": 0.7711,
      "crossover_k": 256
    },
    "table_title": "The four ways to read the model, ranked (now an apples-to-apples comparison)",
    "strategies_table": [
      {"name": "Standard — read the whole best layer", "features": 1024, "score": 0.776, "best": true},
      {"name": "Several whole layers (top 3 combined)", "features": 3072, "score": 0.771},
      {"name": "Best neurons in one layer (256 of them)", "features": 256, "score": 0.747},
      {"name": "Best neurons pooled across layers (256)", "features": 256, "score": 0.745}
    ],
    "heatmap_img": "assets/vjepa2_unit_heatmap.png",
    "cachebust": "2",
    "heatmap_caption": "A map of how well each individual neuron, layer by layer, predicts the brain (brighter = better). The best neurons sit in the middle-to-late layers, but the curve on the right shows the twist: once you read a few hundred of them together, hand-picking the best stops mattering, because the signal is spread across the whole layer.",
    "reading": "Done properly, a clear winner emerges. (1) THE SIMPLEST WAY WINS: reading the whole best layer scores 0.78 out of a possible 1.0, and nothing beats it. (The earlier impression that 'hand-picking the best neurons' won was purely an artefact of an untuned readout; with the readout tuned properly it disappears.) (2) HAND-PICKING ONLY HELPS WHEN YOU MUST BE COMPACT: with just 16 neurons, the best ones crush a random 16 (0.62 vs 0.47), but that edge shrinks as you add more, and by about 256 neurons (a quarter of the layer) picking the best is no better than picking at random, because the signal is spread redundantly across the layer. (3) SPREADING ACROSS LAYERS DOESN'T HELP HERE: the single best layer already holds the signal, so pooling across the top layers (or reading several whole layers) lands a hair lower, not higher. Bottom line for this model: use the whole best layer for the best score, and reach for neuron-picking only when you need a small, fast readout and can trade a sliver of accuracy. (This is the opposite of the dyslexia experiment, where picking the right neurons mattered at every size; there the signal lived in special, localised 'reading' neurons.)",
    "deep_dive": {
      "title": "Going deeper: is one layer really enough? (three stress-tests)",
      "lead": "\"One layer is plenty\" is a surprising result, so we checked it three ways, and they all point to the same simple reason.",
      "cards": [
        {"stat": "+0.01", "title": "Combine all 24 layers, optimally", "body": "We let a method blend all 24 layers with the best possible per-layer weights. It beats the single best layer by only a hair (0.785 vs 0.776). So even the smartest way of combining layers barely helps: one layer already has nearly everything."},
        {"stat": "≈14", "title": "effective dimensions in the signal", "body": "This brain area's response to the clips boils down to only about 14 effective dimensions, and the model's features are about the same width (≈13). One layer already captures them, which is exactly why one layer is enough and why a random handful of neurons does nearly as well."},
        {"stat": "0.78 → 0.01", "title": "Scramble test (sanity check)", "body": "Shuffle which clip goes with which brain response, and the score collapses to almost nothing. Proof that the scores above are real signal, not the method finding shapes in noise."}
      ],
      "pc_chart": {
        "title": "How well the model predicts each of the brain's main patterns",
        "x_title": "the brain's patterns, most common → least",
        "y_title": "match (0–1)",
        "labels": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
        "r": [0.78,0.86,0.84,0.79,0.71,0.60,0.73,0.74,0.61,0.53,0.68,0.61,0.54,0.63,0.64,0.32,0.29,0.53,0.44,0.48],
        "caption": "The model nails the brain's most prominent patterns (the first four at 78–86%) and fades out toward the rarer ones. In total about 35 of the brain's patterns are predictable; that handful is the entire brain-matching signal, which is why one well-chosen layer captures it all."
      }
    }
  },
  "generalize": {
    "title": "Does this hold up beyond one benchmark?",
    "subtitle": "We re-ran the whole layer-mapping analysis across six brain datasets (single neurons and fMRI; seeing, reading, watching short video), five kinds of AI model, and a dataset 12× larger than the others. The same picture held up everywhere, and the one thing we expected to change it didn't.",
    "dim_title": "The brain signal stays simple, no matter how much data you throw at it",
    "dim_note": "Each brain area's response to images boils down to only about 10–22 effective dimensions. Crucially, feeding the analysis 25× more pictures (243 → 6,000) doesn't raise that number, so it's a real property of the brain, not a shortage of data. This is exactly why a single well-chosen model layer is enough to capture it, everywhere we looked.",
    "dim_bars": [
      {"label": "reading sentences", "n": 243, "dim": 21.5},
      {"label": "natural scenes (NSD)", "n": 515, "dim": 20.1},
      {"label": "short video", "n": 1026, "dim": 14.0},
      {"label": "objects", "n": 3200, "dim": 16.3},
      {"label": "7T natural scenes", "n": 6000, "dim": 14.3}
    ],
    "hier_title": "Deeper brain areas line up with deeper model layers",
    "hier_note": "When a dataset covers the full visual ladder, V1 (first stop) through IT (last), the brain's processing stages match the model's: early areas align with early layers, late areas with late layers. A plain image-recognition network (a CNN) shows it most cleanly; an image-text model (CLIP) shows a flatter, compressed version. (This is why one benchmark with only late areas couldn't see it: you need the whole ladder.)",
    "hier_rois": ["V1", "V2", "V4", "IT"],
    "hier_lines": [
      {"name": "CNN (ResNet-50)", "depth": [0.0, 0.0, 0.33, 0.67], "color": "#1f9d57"},
      {"name": "image model (CLIP)", "depth": [0.36, 0.36, 0.36, 0.45], "color": "#2f6bff"}
    ],
    "reading": "Three findings held across every dataset, model, and scale we tried. (1) The brain's response to images is LOW-DIMENSIONAL, about 10–22 effective dimensions per area, and pouring in 12× more high-quality data (a 7-Tesla scanner, 6,000 images) didn't budge it. We even confirmed it replicates across separate people. (2) Because the signal is that simple, a single well-chosen layer captures essentially all of it; elaborate 'combine many layers' or 'hand-pick the best neurons' schemes barely help. (3) Deeper brain areas match deeper model layers (V1→IT lines up with early→late), cleanest for a plain CNN. The one twist worth flagging: HOW you score matters. Measuring 'can the model predict the brain' versus 'does the model's internal geometry match the brain' can flip which model looks most brain-like, and even whether hand-picking neurons helps (it helps for vision, hurts for language). So the honest move is to report both."
  },
  "fusion_compare": {
    "title": "One model that sees + hears + reads together, vs. three separate specialists",
    "subtitle": "To predict a brain watching a movie, you can feed the predictor features two ways. POST-HOC ('TRIBEv2'): run three separate AI specialists (one for the picture, one for the sound, one for the words) and combine their outputs. NATIVE ('MIRAGE', built on a model called Qwen3-Omni): use one big model that takes picture, sound, and words in together, so the senses mix inside it. Everything downstream is identical, so the only thing that changes is which set of features. The question: does mixing the senses inside one model beat three good specialists?",
    "appr_title": "How well each option predicts the brain (each at its best setting)",
    "bars": [
      {"name": "V-JEPA-2+Wav2Vec-Bert+Llama (TRIBEv2), best layers", "kind": "posthoc", "fusion": "post-hoc", "dim": 5120, "r": 0.1564, "extract_min": 29.6},
      {"name": "Qwen3-Omni-30B (MIRAGE), best layer (42)", "kind": "native", "fusion": "native", "dim": 2048, "r": 0.1546, "extract_min": 67.7},
      {"name": "V-JEPA-2 video (best L14)", "kind": "modality", "fusion": "unimodal", "dim": 1024, "r": 0.127, "extract_min": 26.8},
      {"name": "Wav2Vec-Bert audio (best L12)", "kind": "modality", "fusion": "unimodal", "dim": 1024, "r": 0.1238, "extract_min": 1.6},
      {"name": "Llama-3.2-3B text (best L14)", "kind": "modality", "fusion": "unimodal", "dim": 3072, "r": 0.079, "extract_min": 1.2}
    ],
    "reading": "Answer: it's a tie. The three separate encoders combined score 0.156; the single native multimodal model scores 0.155, too close to call. So mixing the senses inside a single (much larger) model doesn't beat three strong specialists here. A wrinkle worth flagging, because it shows why care matters: our first pass made the combined model look slightly ahead, but that was a measurement slip. We'd been reading the audio specialist at the wrong internal spot (its very last stage), where it predicts the brain poorly (0.088); reading it at its best stage nearly doubles its score (0.124) and the apparent lead vanishes. Of the three senses, the picture and the sound carry most of the signal (0.127 and 0.124); the dialogue carries less (0.079), which makes sense for a Friends clip that's mostly driven by what you see and hear. Bottom line: a well-tuned set of separate specialists matches the big native multimodal model, and costs far less to run (about 30 minutes on an ordinary GPU vs. over an hour on four high-end ones).",
    "caveat": "The tie can't be pinned entirely on 'mixing the senses,' because the two sides are different models of different sizes, so 'a strong specialist stack ties the native multimodal model' is the fair reading, not 'mixing the senses is useless.' For clean proof that mixing DOES help, see the curve below: it reads the SAME native multimodal model at successive internal stages, so nothing changes except how much the senses have been combined, and the prediction climbs from 0.123 (before they're mixed) to 0.155 (after). So mixing helps inside the model; it just ends up only matching the three separate encoders, because each specialist is individually stronger than that model's own built-in sense-detectors. All the scores here (~0.15) are floors, not final numbers: they use one person and a small slice of the data, a single internal stage per model, and a simple predictor rather than a fully-trained one.",
    "within_qwen": {
      "layers": [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
      "r": [0.1233, 0.127, 0.1281, 0.1303, 0.1323, 0.1353, 0.1383, 0.1388, 0.1387, 0.1412, 0.1437, 0.1477, 0.1499, 0.1511, 0.152, 0.1531, 0.1524, 0.1532, 0.1534, 0.1529, 0.1542, 0.1546, 0.1537, 0.1522, 0.1429],
      "peak_layer": 42, "fusion_off_r": 0.1233, "peak_r": 0.1546
    },
    "curve_caption": "Reading the one native multimodal model at successive internal stages (left = early, right = late). At the very start, before it has combined the picture, sound, and words, it predicts the brain worst (0.123). As you go deeper and the senses get mixed together, the prediction steadily improves, peaking near the end (0.155). The climb is the value of combining the senses, and because it's the exact same model start to finish, nothing else can explain it. (It dips at the very last stage, where the model shifts to its own job of predicting the next word.)"
  },
  "models_glossary": {
    "title": "The models, in plain terms",
    "subtitle": "A quick who's-who of every AI model on this page and what it's built to do",
    "models": [
      {"name": "CLIP", "kind": "small image model", "desc": "A small, fast model that learned by matching photos to their captions. Handles images well and is our lightweight baseline, and, surprisingly, often the most brain-like on vision."},
      {"name": "BLIP-2", "kind": "image-captioning model", "desc": "A larger model built to describe pictures in words. It's good at captioning but wasn't trained to follow instructions, so it can't reliably answer a direct question."},
      {"name": "Qwen2.5-VL (3B / 7B / 32B)", "kind": "vision-language model (VLM)", "desc": "A model that looks at images and answers questions about them, in three sizes (small / medium / large). The strongest reader here, and the one big enough to show the 'dyslexia' effect when we switch off its word-selective units."},
      {"name": "GPT-2", "kind": "text-only model", "desc": "A small model that only reads text, with no vision at all. Notably, it tells real words from fake ones as well as humans do, working purely from the letters."},
      {"name": "V-JEPA / V-JEPA2", "kind": "video models", "desc": "Video models that learned by predicting their own internal picture of a scene (rather than the exact pixels). The best at predicting a brain watching video."},
      {"name": "VideoMAE", "kind": "video model", "desc": "A video model that learned by reproducing exact pixels. Handles motion, but its pixel-copying training transfers less well to predicting the brain."},
      {"name": "Wav2Vec2 · MiniLM", "kind": "a sound model + a text model", "desc": "The audio encoder (a speech/sound model) and the text encoder (a sentence-embedding model), used with a video encoder to predict a brain watching a full movie."},
      {"name": "random-ViT", "kind": "sanity-check floor", "desc": "An untrained model with the same wiring as CLIP, but its connections are random noise. Shows how high a score you can get from nothing (~0.54 on the word task)."},
      {"name": "chance", "kind": "sanity-check floor", "desc": "A 'model' that just guesses, ignoring its input entirely. The rock-bottom floor, 0.50 on a yes/no task."},
      {"name": "oracle", "kind": "perfect-player ceiling", "desc": "A built-in cheat that always makes the perfect move in the video game. Defines the best possible score: the ceiling everything else is measured against."}
    ]
  },
  "embodied_game": {
    "title": "A VLM plays a video game",
    "subtitle": "The same single hand-off that runs the brain tests also lets a model play a game: it sees a picture of the board, decides a move, the game updates, and round it goes, hundreds of times. This isn't a brain-alignment measure; it shows that one interface (the same single hand-off) spans perception and action. It's scored against a perfect player (the ceiling) and random moves (the floor).",
    "models": ["random moves", "Qwen-VL 3B (CoT)", "Qwen-VL 7B (CoT)", "Gemma-4 12B (CoT)", "DeepSeek-R1 (ASCII)", "perfect player"],
    "success": [0.20, 0.0, 0.533, 1.0, 0.867, 1.0],
    "colors": ["#9aa0a6", "#d8483b", "#e0a13b", "#2a8c6a", "#7c4dff", "#1f9d57"],
    "null_floor": 0.20,
    "reading": "Two findings. (1) HOW you ask matters: when the medium model is forced to answer in one word it wins only 13% of games; let it use chain-of-thought and it wins 53%. (2) BIGGER MODELS SEE BETTER: the three VLMs, all looking at the same picture of the board and all using chain-of-thought, win 0% (small), 53% (medium), and 100% (large). Hand the very same board to a text-only model as an ASCII grid instead of an image, and it wins 87%. So for the smaller models the bottleneck isn't figuring out the right move, it's reading the board off the picture in the first place, and that clears up as the models get bigger."
  },
  "layer_contribution": {
    "title": "Where in each model the brain-like signal lives",
    "subtitle": "Each of the three encoders (audio, text, video) is built as a stack of layers. This shows how brain-like each layer is, from the model's input (left) to its output (right); brighter means more brain-like.",
    "order": ["audio", "text", "video"],
    "labels": ["sound (Wav2Vec2)", "words (MiniLM)", "video (CLIP)"],
    "values": {
      "audio": [0.129, 0.143, 0.148, 0.149, 0.148, 0.146, 0.149, 0.152, 0.152, 0.146, 0.137, 0.13, 0.119],
      "text": [0.107, 0.124, 0.129, 0.129, 0.126, 0.124, 0.117],
      "video": [0.041, 0.053, 0.056, 0.07, 0.094, 0.11, 0.117, 0.126, 0.131, 0.145, 0.161, 0.166, 0.168]
    },
    "reading": "The three models don't carry their brain-like signal in the same place. The words model is most brain-like early on (around its 3rd layer), the sound model in its middle (layer 7), and the video model right at the very end (its last layer). Each square is measured directly (how well that one layer predicts the brain) and each row is scaled to show its own shape, so you're comparing where each model peaks, not which model wins."
  },
  "all_paths": {
    "title": "The same word task, scored through every way a model can answer",
    "subtitle": "Telling real words from fake ones (the dyslexia-screening task). A model can answer in different ways (by reading its internal features, by writing out an answer, or both) and the same single setup tries whichever ways each model supports.",
    "chance": 0.5,
    "null_floor": 0.54,
    "pathColors": {"readout": "#3b7dd8", "generation": "#e0a13b", "instr-readout": "#7c5bff"},
    "models": ["chance", "random-ViT", "CLIP", "GPT-2", "BLIP-2", "Qwen"],
    "rows": [
      {"model": "CLIP", "input": "image", "path": "readout", "score": 0.680},
      {"model": "BLIP-2", "input": "image", "path": "readout", "score": 0.790},
      {"model": "BLIP-2", "input": "image", "path": "generation", "score": 0.500},
      {"model": "BLIP-2", "input": "text", "path": "generation", "score": 0.480},
      {"model": "BLIP-2", "input": "image + instruct", "path": "instr-readout", "score": 0.920},
      {"model": "Qwen", "input": "image", "path": "readout", "score": 0.740},
      {"model": "Qwen", "input": "image", "path": "generation", "score": 0.930},
      {"model": "Qwen", "input": "text", "path": "generation", "score": 0.940},
      {"model": "Qwen", "input": "image + instruct", "path": "instr-readout", "score": 0.980},
      {"model": "GPT-2", "input": "text", "path": "readout", "score": 0.810},
      {"model": "GPT-2", "input": "text", "path": "generation", "score": 0.850},
      {"model": "random-ViT", "input": "image", "path": "readout", "score": 0.540},
      {"model": "chance", "input": "—", "path": "readout", "score": 0.500}
    ],
    "reading": "How a model answers can matter as much as which model it is. Take Qwen, unchanged, asked three different ways: reading its raw visual features gets 0.74, writing out an answer gets 0.93, and reading its features after it has 'thought about' the question in words gets 0.98. The language side is where the reading really happens. BLIP-2 is revealing: asked to write an answer it falls to pure guessing (0.50, since it was never trained to follow instructions), yet the right answer is clearly sitting in its features (0.92); it just can't say it out loud. And GPT-2, which only ever sees text, does well both ways (0.81 and 0.85): it simply considers real words far more likely than fake ones. Colour marks how the model answered; the table breaks it down by what it was shown, how it answered, and the score."
  },
  "benchmark_mechanics": {
    "title": "What one of these tests actually does",
    "subtitle": "A walk-through of the word task, and why even a model that can't 'talk', like CLIP, can take it",
    "task": "Each trial shows a picture of a letter string, a real word like 'animal' or a fake one like 'accastant', and the model has to decide which it is. There are 400 practice trials and 100 graded ones; scoring below 65% is the threshold a person would be flagged as dyslexic.",
    "paths": [
      {"name": "Reading its features", "models": "CLIP, GPT-2, any model", "how": "We look at the model's internal response to each letter string and train a simple yes/no rule on the 400 practice trials, then test it. The model never says a word; its internal response just has to look different for real words versus fake ones."},
      {"name": "Writing an answer", "models": "Qwen, BLIP-2, instruction-following models", "how": "We show the image and literally ask 'is this a real word?', then read the model's written reply. This only works for models trained to follow instructions, and it's the path the original dyslexia study used."}
    ],
    "floors": [
      {"label": "guessing", "value": 0.50},
      {"label": "untrained model", "value": 0.54},
      {"label": "CLIP", "value": 0.68}
    ],
    "answer": "CLIP scores 0.68 by the first route, reading its features, even though it can't write an answer. Its caption-matching training left it sensitive to what real words look like. The honest way to read that 0.68 is against the floors: pure guessing is 0.50 and an untrained model is 0.54, so CLIP's score is +0.14 of genuine learned word-knowledge above what you'd get for free, not the scoring trick overfitting."
  },
  "inputs": [
    {"type": "image", "example": "a natural photograph", "benchmark": "object-vision brain data (MajajHong 2015)", "desc": "A still photo. This lights up the brain's object-recognition areas (toward the back and bottom), and we test how well a model predicts them."},
    {"type": "text", "example": "a sentence", "benchmark": "sentence-reading brain data (Pereira 2018)", "desc": "A written sentence. This drives the brain's language network (left side), which a text model's responses can predict."},
    {"type": "audio", "example": "a speech / environmental sound clip", "benchmark": "sound brain data (Lahner 2024 · Algonauts)", "desc": "A sound clip. This drives the hearing areas (along the sides), which a speech/sound model can predict."},
    {"type": "video", "example": "a 3-second clip", "benchmark": "short-video brain data (Lahner 2024)", "desc": "A short video. This drives the motion- and object-sensitive visual areas; models built for video do best here."},
    {"type": "video + audio", "example": "a movie segment", "benchmark": "movie brain data (Algonauts 2025)", "desc": "Picture plus sound together. Adding the sound extends the prediction from the seeing areas into the hearing areas."},
    {"type": "video + audio + text", "example": "a movie scene with dialogue + subtitles", "benchmark": "movie brain data (Algonauts 2025)", "desc": "The full movie experience: picture, sound, and dialogue. Together these drive much of the brain, and combining all three predicts it best. This is the real movie-watching test."}
  ],
  "witness": {
    "title": "Looking over the model's shoulder",
    "subtitle": "Because every kind of test (seeing, reading, listening, playing, being lesioned) runs through the same single hand-off, we can watch that one spot and see any test unfold: what the model was shown, and what it did with it (its internal response, its answer, or its move). These are real recordings, captured with no test-specific code.",
    "modes": ["recording brain-like activity", "reading its features", "writing an answer", "taking an action", "switching neurons off"],
    "panels": [
      {"img": "assets/witness_game_0.png", "caption": "The model is shown the game board and we log what it DID, its move: down. Captured straight from the game, with no code special to the game."},
      {"img": "assets/witness_game_2.png", "caption": "A later moment in the same game. One recorder, one format, for every test, whether the model is looking, reading, listening, playing, or being lesioned."}
    ],
    "reading": "We attach a quiet observer that, for the length of a test, notes one entry every time the model is handed something. Because every capability flows through that single point, this one observer covers them all: the same kind of record whether the model is looking at images, reading sentences, playing a game, or having its neurons switched off."
  },
  "percept": {
    "title": "What the model ACTUALLY saw",
    "subtitle": "The image we hand a model isn't quite the image it sees. Before it reaches the model, every picture gets shrunk, cropped to a square, and colour-adjusted. This tool catches the picture at that final moment, right as it enters the model, and shows it back to us. The reveal: the cropping can quietly cut away parts of the image, so 'what we showed' and 'what the model saw' aren't the same.",
    "tabs": [
      {
        "id": "crop",
        "label": "Shrink & crop",
        "columns": ["what we showed", "raw form (not viewable)", "what the model saw"],
        "rows": [
          {"label": "Wide 640×360", "presented": "assets/percept/0_presented.png", "tensor": "assets/percept/0_tensor.png", "percept": "assets/percept/0_percept.png", "note": "The crop to a square throws away the green left edge and gold right edge entirely; the model never saw them. The top and bottom survive."},
          {"label": "Tall 360×640", "presented": "assets/percept/1_presented.png", "tensor": "assets/percept/1_tensor.png", "percept": "assets/percept/1_percept.png", "note": "Now it's the top and bottom that get cut and the left/right edges that survive: the crop flips depending on the picture's shape."},
          {"label": "Square 360×360", "presented": "assets/percept/2_presented.png", "tensor": "assets/percept/2_tensor.png", "percept": "assets/percept/2_percept.png", "note": "A square picture needs no cropping; all four edges survive, only the shrink happens. The colours come back faithfully once we undo the colour-adjustment."}
        ],
        "reading": "Left = the picture we handed in. Middle = the colour-adjusted form the model actually works in, false-coloured and not meant for human eyes, which is exactly why we have to reconstruct it. Right = our reconstruction, undoing the colour-adjustment. The thing to notice is the difference between left and right: the crop genuinely removes pieces of the picture (the labelled edges), so 'what we showed' and 'what the model saw' are not the same image.",
        "caveat": "This panel uses CLIP's exact shrink-and-crop recipe; that's a property of the preparation step, not the model's intelligence, so no actual model weights are needed to demonstrate it. The tool captures this same picture on a real model; it shows the input going in, not the model's internal thoughts afterward."
      },
      {
        "id": "rajalingham",
        "label": "Rajalingham 2018 matching task",
        "columns": ["what we showed", "raw form (not viewable)", "what the model saw"],
        "rows": [
          {"label": "Trial 0 (502×586)", "presented": "assets/raj2afc_montage_0.png", "tensor": "assets/percept/raj0_tensor.png", "percept": "assets/percept/raj0_percept.png", "note": "The crop trims the 'SAMPLE' caption at the top and the 'LEFT'/'RIGHT' captions at the bottom, but the sample picture and both choices survive untouched."},
          {"label": "Trial 2 (502×586)", "presented": "assets/raj2afc_montage_2.png", "tensor": "assets/percept/raj1_tensor.png", "percept": "assets/percept/raj1_percept.png", "note": "Same layout, same trim. Everything needed to make the choice survives; only the text captions at the very top and bottom are cut."}
        ],
        "reading": "This is the picture CLIP actually saw on the object-matching task. The shrink-and-crop trims the text captions at the top and bottom ('SAMPLE', 'LEFT', 'RIGHT') while the sample picture and the two choices come through intact. So the model made its choice from the pictures themselves, not by reading the printed labels, something you'd only know by reconstructing what it really took in.",
        "caveat": "This is specifically CLIP's view. The chat-style models (Qwen, Gemma) don't crop to a square; they shrink the whole thing, so they saw the full picture including every caption. This panel doesn't represent what those models saw."
      },
      {
        "id": "multimodal",
        "label": "Image + words together",
        "columns": ["what we showed", "the form it's stored in", "what the model saw"],
        "rows": [
          {"kind": "image", "label": "The picture side", "presented": "assets/percept/mm_vision_presented.png", "tensor": "assets/percept/mm_vision_tensor.png", "percept": "assets/percept/mm_vision_percept.png", "note": "The picture branch: shrunk and colour-adjusted, then undone for viewing. This, a wrench on a mountainside, is exactly what the model's 'eyes' took in."},
          {"kind": "text", "label": "The words side", "presented": "\"a photo of a wrench on a mountainside\"", "tensor": "[49406, 320, 1125, 539, 320, 30980, 525, 320, 14547, 1145, 49407, … ]  ·  padded out to a fixed length", "percept": "<start> a photo of a wrench on a mountainside <end>  … <end> repeated as padding", "note": "Before a model reads text it chops it into pieces and turns them into numbers. 'wrench' becomes one piece; 'mountainside' is split into two ('mountain' + 'side'). It also tacks on start/end markers and pads to a fixed length, and that's exactly what the model read."}
        ],
        "reading": "A model that handles BOTH a picture and a caption (here CLIP) takes them in through two doors at once. The tool listens at both, catching the picture as pixels and the caption as the numbered word-pieces the model actually reads, and shows each back in its own way: undo the colour-adjustment for the picture, turn the numbers back into words for the text. One mechanism, every kind of input; on a video-and-sound model the same approach would hand back sampled frames and a sound wave.",
        "caveat": "The text 'what the model saw' is the numbered pieces turned back into words, faithful to what the model read (the markers, the split words, the padding), but it's the words reconstructed from those pieces, not an actual picture. Sound comes back as a sound wave, which for some models can't be perfectly turned back into the original audio."
      }
    ]
  },
  "rajalingham": {
    "title": "An object-recognition task (Rajalingham 2018), asked of models several ways",
    "subtitle": "This is the Rajalingham 2018 object-matching benchmark: you're shown a target object for a moment, then two pictures, and you pick the one that matches. We have models do it the real way, actually looking and choosing, exactly as the people and monkeys in the original study did. The score (called i2n) isn't just 'how often right'; it's whether the model finds the SAME pictures hard that people find hard. So a model can be accurate overall yet still score low if it stumbles on different images than humans do. The bar colours mark how we asked: direct = answer right away; think-out-loud = reason step by step first; with-practice = show four solved examples before asking. (Even a flawless single chooser tops out around 0.33 on this score, so every bar here sits well below that ceiling.)",
    "metric": "i2n raw (image-level, vs the human pool)",
    "binary_ceiling": 0.33,
    "readout_band": "~0.30-0.50",
    "rows": [
      {"model": "random null", "mode": "—", "acc": 0.510, "frac_left": null, "i2n": -0.028, "kind": "null"},
      {"model": "CLIP", "mode": "similarity", "acc": 0.662, "frac_left": 0.49, "i2n": 0.061, "kind": "feature"},
      {"model": "Qwen-VL-3B", "mode": "CoT", "acc": 0.497, "frac_left": null, "i2n": 0.006, "kind": "cot"},
      {"model": "Qwen-VL-3B", "mode": "direct", "acc": 0.634, "frac_left": 0.85, "i2n": 0.064, "kind": "direct"},
      {"model": "Qwen-VL-3B", "mode": "direct + 4-shot", "acc": 0.506, "frac_left": 0.99, "i2n": 0.010, "kind": "fewshot"},
      {"model": "Qwen-VL-7B", "mode": "CoT", "acc": 0.562, "frac_left": 0.89, "i2n": 0.031, "kind": "cot"},
      {"model": "Qwen-VL-7B", "mode": "direct", "acc": 0.859, "frac_left": 0.47, "i2n": 0.163, "kind": "direct"},
      {"model": "Qwen-VL-7B", "mode": "direct + 4-shot", "acc": 0.785, "frac_left": 0.63, "i2n": 0.154, "kind": "fewshot"},
      {"model": "Gemma-4-12B", "mode": "direct", "acc": 0.846, "frac_left": 0.45, "i2n": 0.146, "kind": "direct"},
      {"model": "Gemma-4-12B", "mode": "direct + 4-shot", "acc": 0.853, "frac_left": 0.43, "i2n": 0.100, "kind": "fewshot"}
    ],
    "montages": ["assets/raj2afc_montage_0.png", "assets/raj2afc_montage_2.png"],
    "kindColors": {"null": "#9aa0a6", "feature": "#1f9d57", "cot": "#d8483b", "direct": "#2f6bff", "fewshot": "#c6810f"},
    "findings": [
      "How you ask is everything. Answering directly beats chain-of-thought here, and not by a little: making the medium model reason step by step roughly halves its score (0.16 → 0.03) and makes it blurt 'LEFT' almost every time. That's the OPPOSITE of the video game, where chain-of-thought was essential. Reasoning helps when there's a plan to work out, but it gets in the way of just seeing. (We confirmed this by re-running with the choices flipped left/right: the direct version genuinely perceives, the think-out-loud version is basically guessing once you account for its left-leaning habit.)",
      "Bigger models see better. Answering directly, the small model is weak and biased; the medium and large ones are unbiased and genuinely good. A capable model can do this task cold, with no practice.",
      "Practice HURTS here, the opposite of what you'd expect for people. Showing four solved examples first dropped the small model to pure guessing and pulled the large one down too. This visual matching task doesn't benefit from worked examples the way text tasks do.",
      "The approach that wins is the old one: training a small dedicated decision-rule on the model's features (0.30–0.50) still beats the best 'just ask it' result (0.16). A purpose-built rule beats prompting; closing that gap by prompting alone would take actually retraining the model, not a few examples."
    ],
    "reading": "The same task, scored the same way, along three independent dials: model size (small → medium → large), how we ask (think-out-loud vs. answer directly), and how much help we give (none → a few examples → a trained decision-rule). The dashed lines mark the best a single chooser can reach (0.33) and the trained-rule range. We caught a left/right answering bias by tracking how often each model said 'left', and removed it with a balanced re-run.",
    "caveats": [
      "The big caveat: the original people and monkeys chose between clean, canonical object pictures; our choices are messier, harder renders of the same objects. So the models are doing a HARDER version than the humans we compare them to: a low score mixes 'couldn't see it' with 'was given a tougher picture'. The absolute numbers are floors; the comparisons WITHIN this page (direct vs. think-out-loud, size, practice) all use the same pictures and are the trustworthy part.",
      "The trained-rule range (0.30–0.50) is the original benchmark's published number, not re-measured on this small image set; it anchors the scale but isn't a strict apples-to-apples comparison.",
      "We haven't computed error bars yet: with only 120 images, the large-model vs. medium-model gap may not be real, so read the tiers, not the exact decimals.",
      "The 'practice hurts' result might partly be a quirk of how we showed multiple images at once (the small model just kept saying 'left'); it needs one more control before we'd call it a fact."
    ],
    "sequential": {
      "title": "The task, the way the people and monkeys actually saw it",
      "subtitle": "The real task is one-at-a-time: a brief look at the target, then it is hidden, and only THEN do the two choices appear, so you have to hold the target in memory and pick the match. That is the exact sequence the people and monkeys saw. We trace it step by step, because the interesting question is what the model loses when it has to remember the target rather than stare at it. Same model, same 2,505 trials.",
      "trace": [
        {"img": "assets/raj_seq_sample.png", "cap": "1 · target shown, then hidden", "kind": "img"},
        {"text": "the model describes it in its own words, then the target is gone", "cap": "2 · the bottleneck: remember it", "kind": "text"},
        {"img": "assets/raj_seq_choices.png", "cap": "3 · choices appear; target is GONE, so it must match from memory", "kind": "img"}
      ],
      "conditions": [
        {"label": "guessing (floor)", "i2n": -0.028, "kind": "null"},
        {"label": "from memory: target hidden, match from its own description", "i2n": 0.097, "kind": "seq"},
        {"label": "target still on screen: choose with it in view", "i2n": 0.170, "kind": "seq"},
        {"label": "all three on screen at once (a simplification)", "i2n": 0.163, "kind": "sim"}
      ],
      "kindColors": {"null": "#9aa6b8", "seq": "#7c4dff", "sim": "#2f6bff"},
      "reading": "What costs the model is losing sight of the target, not seeing things one at a time. The only fully realistic version, where the target is gone and the model must choose from its own remembered description, drops the score by about 40% (to 0.097). Putting the target into words throws away the fine visual detail the match needs (the descriptions were perfectly fluent, e.g. 'a sculpture of a person in mid-air, diving or jumping', and the model gave a clean left/right answer on all but 5 of 2,505 trials). When the target stays on screen, splitting the task into steps costs almost nothing (0.170 ≈ 0.163), so showing all three at once isn't inflating the score just by keeping everything visible.",
      "caveat": "The small edge of 'target on screen' over 'all at once' is probably just the left/right answering bias again, so treat them as equal. Keeping the target on screen isn't a true test of memory, so the from-memory version is the meaningful realistic one. A balanced re-run would tighten the numbers."
    }
  },
  "gemma_scorecard": {
    "title": "One brand-new model, put through every test",
    "subtitle": "Gemma-4-12B is a free, open model released just this week, with an unusual design (no separate 'vision' part, it reads pixels directly). We wired it in once and ran it through everything: the object-matching task, the word task, the video game, and predicting brain activity, all from a single setup, on one ordinary GPU. The point isn't where it lands on a leaderboard; it's that one new model touched every kind of test the same way.",
    "rows": [
      {"capability": "Seeing · behavior", "benchmark": "Object matching", "metric": "human–model consistency (i2n)", "score": "0.146", "status": "done", "note": "answering directly, no left/right bias; on par with the medium Qwen model"},
      {"capability": "Reading · behavior", "benchmark": "Real vs. fake words", "metric": "accuracy", "score": "0.86", "status": "done", "note": "above the human average; not dyslexic, gets fake words right every time, real words 72%"},
      {"capability": "Playing · video game", "benchmark": "Grid game", "metric": "win rate", "score": "1.00", "status": "done", "note": "won all 15 games perfectly with chain-of-thought, topping the size ladder. On a much harder maze game it scores 0; the two games aren't interchangeable."},
      {"capability": "Seeing · brain", "benchmark": "Predicting vision areas", "metric": "Brain-Score", "score": "V4 0.40 · IT 0.53", "status": "done", "note": "its unusual no-separate-vision design needed a new connector, built and checked this session; the 0.53 is in CLIP's league (measured a bit differently from the public leaderboard, so not a direct comparison)"}
    ],
    "reading": "Because Gemma-4 has no separate vision part (pixels feed straight into the main model) predicting brain activity from it needed a new little connector, which we built and checked this session. After that, all four kinds of test ran from the one setup: the object-matching task, the word task, the video game (a clean sweep, topping the size ladder), and predicting vision-area brain activity (0.40 and 0.53). This scorecard is the whole promise in one picture: wire a model in once, test it on everything, even a model design that's only days old."
  }
};
